import { getTemplateById } from '@/features/templates/configs';
import { fontFamilyFor } from '@/features/templates/services/fonts';
import { resolveTheme } from '@/features/templates/services/resolve-theme';
import type { Menu, MenuItem } from '@/types/menu';
import { formatPrice } from '@/utils/format';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function buildMenuHtml(menu: Menu): string {
  // Printed menus always use the light variant of the active template so PDFs
  // remain legible on paper regardless of the user's current appearance.
  const template = getTemplateById(menu.restaurant.templateId);
  const theme = resolveTheme(template, menu.restaurant.overrides, 'light');
  const palette = theme.colors;
  const headingFont = fontFamilyFor(theme.typography.heading);
  const bodyFont = fontFamilyFor(template.typography.body);
  const priceFont = fontFamilyFor(template.typography.price);
  const { categories, items, restaurant } = menu;

  const sortedCategories = [...categories].sort((a, b) => a.order - b.order);
  const colorFor = (diet: 'veg' | 'nonveg' | 'vegan') => {
    if (diet === 'nonveg') return palette.nonveg;
    if (diet === 'vegan') return palette.vegan;
    return palette.veg;
  };

  const categorySections = sortedCategories
    .map((category) => {
      const catItems = [...items]
        .filter((i) => i.categoryId === category.id && i.available)
        .sort((a, b) => a.order - b.order);

      if (catItems.length === 0) return '';

      const itemRows = catItems
        .map((item: MenuItem) => {
          const dietColor = colorFor(item.diet);
          const desc = item.description
            ? `<p class="desc">${escapeHtml(item.description)}</p>`
            : '';
          return `
            <div class="item">
              <div class="item-head">
                <div class="item-name">
                  <span class="dot" style="background:${dietColor}"></span>
                  ${escapeHtml(item.name)}
                </div>
                <div class="item-price">${escapeHtml(formatPrice(item.price, restaurant.currency))}</div>
              </div>
              ${desc}
            </div>`;
        })
        .join('');

      return `
        <section class="category">
          <h2>${escapeHtml(category.name)}</h2>
          ${itemRows}
        </section>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(restaurant.name)}</title>
<style>
  @page { margin: 24px; }
  * { box-sizing: border-box; }
  body {
    font-family: ${bodyFont};
    color: ${palette.text};
    background: ${palette.background};
    margin: 0; padding: 24px;
  }
  header { text-align: center; padding-bottom: 16px; border-bottom: 2px solid ${palette.border}; margin-bottom: 24px; }
  header h1 { margin: 0; font-size: 32px; font-family: ${headingFont}; font-weight: ${theme.typography.headingWeight}; letter-spacing: ${theme.typography.letterSpacing}px; }
  header p { margin: 4px 0 0; color: ${palette.textMuted}; font-size: 14px; }
  .category { margin-bottom: 24px; page-break-inside: avoid; }
  .category h2 {
    font-family: ${headingFont}; font-size: 18px; text-transform: uppercase; letter-spacing: 1px;
    color: ${palette.accent}; border-bottom: 1px solid ${palette.border};
    padding-bottom: 4px; margin: 0 0 12px;
  }
  .item { padding: 8px 0; border-bottom: 1px dotted ${palette.border}; page-break-inside: avoid; }
  .item:last-child { border-bottom: none; }
  .item-head { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; }
  .item-name { font-weight: 600; font-size: 15px; }
  .item-price { font-family: ${priceFont}; font-weight: 600; font-size: 15px; color: ${palette.price}; white-space: nowrap; }
  .dot { display: inline-block; width: 10px; height: 10px; border-radius: 2px; margin-right: 6px; vertical-align: middle; }
  .desc { margin: 4px 0 0; color: ${palette.textMuted}; font-size: 13px; }
  footer { text-align: center; color: ${palette.textMuted}; font-size: 11px; margin-top: 32px; }
</style>
</head>
<body>
  <header>
    <h1>${escapeHtml(restaurant.name)}</h1>
    ${restaurant.tagline ? `<p>${escapeHtml(restaurant.tagline)}</p>` : ''}
  </header>
  ${categorySections || `<p style="text-align:center;color:${palette.textMuted}">No items yet.</p>`}
  <footer>Generated by MenuBuilder · ${escapeHtml(template.name)}</footer>
</body>
</html>`;
}
